name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa 1x ao dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Atualizado para v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: "josepatobr"  # Corrigido o nome da variável
          outputs: "dist/snake.svg"

      - name: Commit and push the animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          mkdir -p dist
          git add dist/snake.svg
          git commit -m 'Generate snake animation' || echo "No changes to commit"
          git push


